<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page import="java.util.List"%>
<%@ page import="java.util.ArrayList"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="objects.Course"%>
<%@ page import="objects.Time"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Corsola - Design your schedule!</title>
<link rel="stylesheet" type="text/css" href="css/demo.css" />
<link rel="stylesheet" type="text/css" href="css/style.css" />
<link rel="stylesheet" type="text/css" href="css/animate-custom.css" />
<link rel="stylesheet" href="css/selection.css" type="text/css" />
<script>
function getcourses()
{
alert(document.forms["selectedcourses"]["courses"].value + "!")
}
function reviseButton()
{
	form = document.getElementById("exportForm");
	form.action = "PreferredCourses";
	form.submit();
	}
function exportButton()
{	
	form = document.getElementById("exportForm");
	form.action = "ExportServlet";
	form.submit();
	}
</script>
</head>
<body>
	<div class="container">
		<div class="codrops-top">
			<a href="index.html"> <strong>&laquo; Back Home </strong></a>
			<div class="clr"></div>
		</div>
		<header> <!-- <section>
				<div id="navbar">
					<ul id="list-nav">
						<li id="first"><a href="#">Home</a></li>
						<li><a href="#">About Us</a></li>
						<li><a href="#">Services</a></li>
						<li><a href="#">Products</a></li>
						<li id="last"><a href="#">Contact</a></li>
					</ul>
				</div>
			</section>
			<br> <br> <br>  -->
		<h1 style="font-size: 60px;">&lt;Corsola&gt;</h1>
		<h2>
			<span>Scheduling your life.</span>
		</h2>
		</header>
		<div id="scheduleContainer">
			<div id="header">
				<div>TIME</div>
				<c:forTokens items="MON,TUE,WED,THU,FRI" delims="," var="day">
					<!-- Richard -->
					<div>
						<c:out value="${day}" />
						<!-- Richard -->
					</div>
				</c:forTokens>
				<!-- Richard -->
			</div>
			<!-- Possibly at some point these will come from an init parameter or a servlet? -->
			<c:set var="startTime" value="${8*60}" scope="page" />
			<!-- Richard -->
			<c:set var="endTime" value="${17*60}" scope="page" />
			<!-- Richard -->
			<div id="times">
				<c:forTokens
					items="8:00,9:00,10:00,11:00,12:00,1:00,2:00,3:00,4:00,5:00"
					delims="," var="time">
					<!-- Richard -->
					<div class="time">
						<c:out value="${time}" />
						<!-- Richard -->
					</div>
				</c:forTokens>


			</div>
			<c:forTokens items="monday,tuesday,wednesday,thursday,friday"
				delims="," var="day">
				<div class="day" id="${day}"></div>
			</c:forTokens>
		</div>

		<form id="exportForm" method="post">
				<div id="control">
					<div class="button">
						<input type="submit" value="ReviseList"
							onclick="return reviseButton();"
							style="height: 2em; width: 10em; background: lightblue;" />
					</div>
					<div class="button">
						<input type="submit" value="ExportSchedule"
							onclick="return exportButton();"
							style="height: 2em; width: 10em; background: lightblue;" />
					</div>
				</div>
			<div id="preferred"></div>
				<script src="javascript/jquery-1.9.1.js" type="text/javascript"></script>
				<script src="javascript/jquery-ui-1.10.3.custom.min.js"
					type="text/javascript"></script>

				<script>
	BEGIN_TIME = <c:out value = "${startTime}" />; /*Richard*/
	TOTAL_HEIGHT = 500;
	END_TIME = <c:out value = "${endTime}" />; /*Richard*/
	MINUTE_HEIGHT = TOTAL_HEIGHT / (END_TIME - BEGIN_TIME);
	$('#scheduleContainer').css("height",TOTAL_HEIGHT);
	$('#scheduleContainer').css("width",TOTAL_HEIGHT*1.4);
	
	$('#times').css("height",TOTAL_HEIGHT);
 	$('.day').css("height",TOTAL_HEIGHT);
 	$('.time').css("height",MINUTE_HEIGHT*60);
	
	dayDiv = {
		"M" : $('#monday'),
		"T" : $('#tuesday'),
		"W" : $('#wednesday'),
		"R" : $('#thursday'),
		"F" : $('#friday'),
		"Z" : $('<div/>') /* For undefined days */
	};

	preferredDiv = $('#preferredList');
</script>


				<script src="javascript/selectionList.js" type="text/javascript">

</script>
		</form>
		<script>
	/* Something like the following to be generated by the servlet:
	 deselectedCourses = [Course(1, "PSYC", "113", "01", "psychology", 
	 [new timeBlock("M", 9*60 + 5, 10*60),
	 new timeBlock("T", 9*60 + 5, 10*60),
	 new timeBlock("W", 9*60 + 5, 10*60),
	 new timeBlock("R", 9*60 + 5, 10*60),
	 new timeBlock("F", 9*60 + 5, 10*60)]),
	 new course(2, "CSCI", "335", "01", "computer science", 
	 [new timeBlock("M", 10*60 + 10, 12*60 + 10),
	 new timeBlock("T", 10*60 + 10, 12*60 + 10),
	 new timeBlock("W", 10*60 + 10, 12*60 + 10),
	 new timeBlock("R", 10*60 + 10, 12*60 + 10),
	 new timeBlock("T", 13*60 + 30, 15*60 + 30),
	 new timeBlock("R", 13*60 + 30, 15*60 + 30)])
	 ];
	 */

<%List<Course> courses = (ArrayList<Course>) request.getAttribute("courses");
	 String colors = Course.generateColorList(courses.size());%>
colors = <%=colors%>



timeId = 0;
selectedCourses = [];
courseMap = {}
		<c:forEach var="course" items="${courses}">
		<c:out value="courseMap[${course.id}] = new Course(${course.id}, \"${course.department}\", \"${course.number}\", \"${course.section}\", \"${course.title}\");" escapeXml="false" />
			<c:forEach var="time" items="${course.times}">
			<c:out value="courseMap[${course.id}].addTime(new Time(\"${time.day}\", ${time.starttime}, ${time.endtime}));" escapeXml="false" />
			</c:forEach>
			<c:out value = "courseMap[${course.id}].addPrettyTimes();" />
			</c:forEach>
<c:set var="delimOuter" value="" />
courses = [
<c:forEach var="course" items="${courses}"> 
           <c:out value="${delimOuter}" /> 
           <c:set var="delimOuter" value="," /> 
           <c:out value="${course.id}" /> </c:forEach>];
<!--Alicia -->
</script>
	</div>
</body>
</html>